apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: mixed-deployment-nodepool
spec:
  template:
    metadata:
      labels:
        deployment-type: mixed-sg-pods
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: mixed-deployment-nodeclass
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["m5.large", "m5.xlarge", "m5.2xlarge", "c6i.large", "c6i.xlarge", "c6i.2xlarge"]
      taints:
      - key: mixed-deploymen
        value: "true"
        effect: NoSchedule
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
