apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: validation-nodepool-v3
spec:
  template:
    metadata:
      labels:
        node-type: "validation-v3"
        managed-by: "karpenter"
        version: "v3"
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: 
            - "r5.large"
            - "r5.xlarge"
            - "r6i.large"
            - "r6i.xlarge"
            - "m5.large"
            - "m7i.2xlarge"
            - "c5.4xlarge"
            - "c6i.large"
            - "t3.small"
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: dynamic-maxpods-nodeclass-v3
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
