apiVersion: v1
kind: Pod
metadata:
  name: test-m5-validation
  labels:
    app: test-m5-validation
    test-type: trunk-eni-validation
spec:
  nodeSelector:
    node-type: m5-dynamic-v2
  # Force M5 instance selection
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values: ["m5.large", "m5.xlarge"]
  containers:
  - name: validation-container
    image: nginx:alpine
    resources:
      requests:
        cpu: 2500m     # Target m5.xlarge
        memory: 8Gi    
      limits:
        cpu: 3000m
        memory: 10Gi
    ports:
    - containerPort: 80
    env:
    - name: TEST_TYPE
      value: "m5-trunk-eni-validation"
    - name: EXPECTED_BEHAVIOR
      value: "eni-reservation-applied"
  restartPolicy: Always
